//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInformation
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AccountNumber { get; set; }
        public string UserPassword { get; set; }
        public int Balance { get; set; }
        public int Deposit { get; set; }
        public int Withdraw { get; set; }
    }
}
